### ISSUE TITLE
how can i add multiple images in  ProductController?

### ISSUE THREAD

**Issue by black10manda** [MdMostaFizurRahaman/ecommerce#1]
`if ($request->images) {

                foreach ($request->images as $image) {

                    $product->addMediaFromBase64($image)->toMediaCollection('product-photo');

                }

}`

I am trying with this but the images are deleted and only the last one is left, if someone can help me I would appreciate it

**Comment by mostafizurhimself** [comment]
On `Product` model media is registered as a single collection.

```php
    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('product-photo')->singleFile();
    }
```
You need to change it like this, 

```php
    public function registerMediaCollections(): void
    {
        $this->addMediaCollection('product-photo');
    }
```
