### ISSUE TITLE
Can't login with super-admin

### ISSUE THREAD

**Issue by Abdulhadi77** [MdMostaFizurRahaman/ecommerce#2]
I create super-admin using the command line but I can't login

**Comment by mostafizurhimself** [comment]
Check your `DB` and make sure that super-admin is created.

**Comment by mostafizurhimself** [comment]
Super admin generation command: 
`php artisan generate:super-admin`

**Comment by Abdulhadi77** [comment]
I checked my DB and the super-admin is created, but it gives me email or password incorrect

**Comment by mostafizurhimself** [comment]
We already checked from our site. Everything is good here. Would you please share some screenshots/screencast of the errors.

**Comment by Abdulhadi77** [comment]
![eq](https://user-images.githubusercontent.com/26086094/186384871-92b06c90-b042-4985-a7df-5aef2898bda7.PNG)

I am sure about the email and password.

Maybe because I use this http://localhost:3000/login to login to dashboard using super-admin? Is there any specific route to login to dashboard?

**Comment by mostafizurhimself** [comment]
I think you are trying to log in from the wrong URL. Admin login URL is `http://localhost:3000/admin/login`

![image](https://user-images.githubusercontent.com/42089253/186430690-e4b7dd8d-1862-42e2-88bb-ef0691b2582b.png)

![image](https://user-images.githubusercontent.com/42089253/186430518-683cdda8-7c7b-4eed-a586-e5a664d4770a.png)

**Comment by mostafizurhimself** [comment]
I will update the `README.md`
