### ISSUE TITLE
Retrieve "Server error" when run "npm run generate

### ISSUE THREAD

**Issue by muoiplus** [MdMostaFizurRahaman/ecommerce#4]
Hi there,

I'm beginner in nuxt,
I've met some error when try to build your project (please check the screenshot)
Could you please help me to check the issues and give me some advises?

My API url: https://shopapi.favistore.com/api
My frontend url: https://shop.favistore.com/api

Thank you so much!
![image](https://user-images.githubusercontent.com/7223740/192290790-eeb65c47-e504-431e-8f82-daec4da20118.png)

**Comment by mostafizurhimself** [comment]
To build the app, go to the `frontend` folder and run the following command 
```
npm run build
```

**Comment by muoiplus** [comment]
I've run build command already
1. npm run build
2. npm run generate
Then I got errors

**Comment by mostafizurhimself** [comment]
Why do you want to run `npm run generate` command?

**Comment by muoiplus** [comment]
I'd like build this project on VPS, can access through domain instead of localhost:3000

**Comment by mostafizurhimself** [comment]
This is an SSR app. So you have to run this with node server. You can use [pm2](https://www.npmjs.com/package/pm2) for this purpose. Then with `nginx` server you can proxy `http:localhost:3000` with your domain
